### ISSUE TITLE
prune sql currently used by SBC, add for v1

### ISSUE THREAD

**Issue by mobb** [lter/LTER-core-metabase#1]

**Comment by mobb** [comment]
schema only

**Comment by mobb** [comment]
using the MBON version as originally planned.

**Comment by mobb** [comment]
whoops, its a hybrid! 
- schemas from sbc mbon: metabase, mb2eml_r 
- schema from sbc lter: pkg_mgmt

**Comment by mobb** [comment]
TO DO 

- [ ] extract the three schemas, assemble into one sql
- [ ] sandbox it 
- [ ] add comments (tables and columns)
- [ ] write a quick-start 
- [ ] commit 
- [ ] assemble more documentation (table descriptions, schemaspy material) 
- [ ] assemble examples (populated tables)

**Comment by gastil** [comment]
As we close this really old issue, a big Thank You to @mobb for getting this going last September!
