### ISSUE TITLE
Is tokenizing %db_owner% necessary?

### ISSUE THREAD

**Issue by twhiteaker** [lter/LTER-core-metabase#17]
In the SQL, instead of 
`OWNER = %db_owner%`
you could have
`OWNER = 'db_owner'`

As far as I can tell, a global search and replace to swap out 'db_owner' with your actual DB owner doesn't break anything, so that's just as easy as replacing %db_owner%. And there's the added benefit that if users just want to test metabase quickly, they can make a 'db_owner' user and thus not have to change anything in the SQL.

**Comment by twhiteaker** [comment]
If we ever want to support continuous integration and unit testing (which I think we should), I think it would be easier to set up without tokenizing usernames...unless there's a way to send Travis CI a one liner that replaces the all the tokens.

**Comment by gastil** [comment]
```
#!/bin/bash
for i in 1 2 3 4 5
do
cat {$i}_script_name | sed 's/%db_owner%/tim/g' > {$i}_script_name_detokenized
done
```
Which you are welcome to remove the line feeds to make a "one liner".

**Comment by atn38** [comment]
closing since we decided on "yes, tokenize" and to declutter
