### ISSUE TITLE
add description of install-scenarios to documentation

### ISSUE THREAD

**Issue by mobb** [lter/LTER-core-metabase#23]
the 5 scripts fit a particular set of install scenarios. list them here

1. institutional/central server 
    1. dbadmin acct that is not the db_owner acct (they may/may not be the same person) 
    2. different accts (people) run different scripts
    3. at least some accounts probably already exist (because the db_owner is likely to have access to other databases)
    4. there may be a sandbox db and a production db (eg, sandbox has example content loaded, production does not)

2. desktop install 
    1. dbadmin and owner are probably the the same person  
    2. multiple ways to install
          - use a gui with an sql pane and run scripts as for a central server
          - concat the scripts together and run them as you would a restore (keep in mind that the typical order of a DB dump-restore is not the order of operations in these scripts)
    4. keep in mind that it is almost impossible to share work this way, which might obviate the use of postgres altogether 

3. optional: notes for install on different OS's (probably orthogonal to the above)

**Comment by atn38** [comment]
@twhiteaker and I wrote up Windows instructions for GUI DBeaver and CLI psql here

https://github.com/BLE-LTER/LTER-core-metabase/blob/verbose/docs/metabase_start_windows.md

**Comment by mobb** [comment]
there is no scenario where a person installing the db does not have to edit something

**Comment by gastil** [comment]
I added this info to the quick_start_guide.md. Not perfect, but the content is there. Closing.
