### ISSUE TITLE
add TaxonomicCoverage

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#25]
as discussed in call

**Comment by atn38** [comment]
See [SQL script on BLE fork](https://github.com/BLE-LTER/LTER-core-metabase/blob/An_stuffystuff/sql/08_create_taxonomiccoverage.sql) for a draft of two tables + a view to begin modeling taxonomic coverage, hopefully can start discussion.

In summary, modelled after the many-to-many model also used in `SiteList` and `DataSetSites`

```
CREATE TABLE lter_metabase."TaxaList" (
	"TaxonID" character varying(20) NOT NULL;
	"TaxonomicAuthority" character varying(20) NOT NULL;
	"TaxonName" character varying(50);
	"TaxonRank" character varying(20);
);

CREATE TABLE lter_metabase."DataSetTaxa" (
	"DataSetID" integer NOT NULL;
	"TaxonID" character varying(20) NOT NULL;
	"TaxonomicAuthority" character varying(20) NOT NULL;
);
```

Motivation to store IDs as primary key instead of names or full taxonomic trees: 
- Less need to update with new names as taxonomies change.
- Resolving to names and authorities and full trees can be done in R (or other language of choice), esp. with the many many R packages for taxonomy right now (Colin's [taxonomyCleanR](https://github.com/EDIorg/taxonomyCleanr) is an EML-focused central interface to many authority-specific R interfaces)
- Resolving to names when done in R and at the point of EML generation will be as up-to-date as can be. 

I'm imagining the workflow with these tables to be:

(1) Take "species" or whatever columns contain taxon-info in data from PI
(2) run through `taxonomyCleanR`
(3) get IDs and authorities
(4) populate metabase 
(5) run through `mb2eml_R` workflow (which will include a call to `taxonomyCleanR` under the hood, to be written)
(6) get EML

@scelmendorf pointed out that for many groups, there are many many spp. the authorities disagree or simply have no record of. `TaxonName`  and `TaxonRank` is a clumsy attempt to take this into account. When this happens, enter a bogus `TaxonID` (which `taxonomyCleanR` will detect). 

Also, per @scelmendorf, it could be helpful to have a boolean column `contains_taxa` in DataSetAttributes. Context is the first step in `taxonomyCleanR` is something like `taxa_map <- create_taxa_map(path = my_path, x = data, col = 'Species')`. Having a record of which column contains taxa info will help during steps (1) and (2) when updating yearly-survey type datasets.

Again this is to start discussion.

**Comment by gastil** [comment]
Semantic Annotation. It's coming in EML 2.2. Lets make our design incorporate that because semantic annotation is ideal for is tagging an attribute column that it contains taxonomic info. Another place I expect to tag with semantic annotation is the taxonomicCoverage. 

(I do not know the proper acronym/abbreviation for semantic annotation so I'm going to use SA.)

At the ASM, Sven and I designed the db tables for SA. I need to look to see if our design lacks particulars to taxonomic uses at those levels (attribute and coverage). Rather than tacking on a column to DataSetAttributes I suggest joining to the semantic annotation table where it will be recorded which columns have what annotation.

**Comment by twhiteaker** [comment]
I strongly approve of designing for EML 2.2 if EML 2.2 has a solution for what we're trying to solve!

**Comment by atn38** [comment]
Awesome, let's shelve the "contains_taxa" column to merge with whatever tables we use for semantic annotation (also see #15). Any feedback on the main two tables + a view? Is there a way to design for EML 2.2 there? Per [EML 2.2 doc here](url), `TaxonID` plus a `provider` attribute is supported in EML 2.2.

**Comment by atn38** [comment]
closing, see pull request #45
