### ISSUE TITLE
Vestigial Columns

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#26]
updated April 9th 2019, add new entries and restructure to group by table
from my POV (R code person), these columns could be vestigial or could benefit from clarified convention:

**1. DataSet**

- Investigator
currently not passed into views
PROPOSE to either (1) enforce constraint that one of "creator" roles in DataSetPersonnel should be identical to Investigator? OR (2) drop column completely

- Accession
Is this meant to contain distribution information at the dataset level? All empty in SBC sample.
Also see #29 for entity-level distribution info. OR is this meant to contain the EDI/other repo package ID? In that case, replicate this from pkg_mgmt.pkg_state.dataset_archive_id

- ProjectRelease/PublicRelease
nothing in SBC sample data

- geographicDescription
VIEWs don't do anything with this. nothing in SBC sample data.

**2. DataSetEntities**

- DataAnomalies
currently not passed into views
is there an EML tag for this kind of info?
Edit: SBC sample data has some info here, eg
`
<para>The text table is 1.6 gb, and has been compressed to 365 mb for download.</para>
`

- EntityRecords
passed into views, but R code counts rows in actual files instead. no enforcement, so right now could be total bogus numbers

**3. DataSetAttributes**

- AttributeID
in SBC sample data AttributeID is identical to ColumnName, but only the latter gets passed into views. AttributeID doesn't appear in EMLAttributeCodeDefinition. Primary keys in both tables use ColumnName

----- DataSetKeywords and DataSetPersonnel look good ------

**4. DataSetMethods**

- effectiveRange
empty in SBC sample. not clear what this does. 

**5. DataSetSites**

- EntitySortOrder
already raised in #20

- GeoCoverageSortOrder
Hunch that this is related to entity-level coverage aka #20 somehow, but right now not clear what this does.

**6. DataSetTemporal**

- EntitySortOrder
already raised in #20 

----- EMLAttributeCodeDefinition, EMLKeywordTypeList, EMLMeasurementScaleList, EMLNumberTypeList, EMLStorageTypeList look good ------

**7. EMLUnitDictionary**

- id
in SBC sample data `id` is identical to `name` but only latter gets passed into VIEWs. Primary key uses `id` however. 

- custom
EDI recommends parsing all units as custom unit according to EML BP, pg. 33 so this is redundant

**8. EMLUnitTypes**

- dimension_power

----- FileTypeList looks good to me ------

**9. KeywordThesaurus**

- ThesaurusSortOrder
passed into view, but doesn't appear in R code. not clear what this does. Primary key and FK in DataSetKeywords use ThesaurusID. 

---- Keywords looks good ----

**10. MeasurementScaleList**

- NonNumericDomain 
not clear what this does. doesn't appear in DataSetAttributes or EML

**11. People**

- Address3

- Phone2

- Fax

- dbupdatetime
not so much odd as only People has it

**13. Peopleidentification**
see #35 

**14. ProtocolList**

**15. SiteList**

- SiteType
PROPOSE to remove. see #36 

- ownership
not clear what this does

- ShapeType
clarify how to use: in SBC sample data, there are "point", "polygon", "rectangle", and "polyline". unclear how "polygon" could be represented differently from "rectangle", and unclear how "polyline" could be represented at all

- CenterLon/CenterLat
not passed into VIEWs. don't appear on EML

- unit
PROPOSE to rename to `altitude_unit`

**Comment by gastil** [comment]
1. 
The metabase table "DataSet" does still have a column "Investigator". This is vestigial from the GCE Metabase. His original data model was 1-to-1 for a lot of things that are now many-to-many. I do populate that column, but only for my own reference, as I tend to associate people with datasets so it makes it faster to find one if I forgot its number. But in my case that is completely redundant info there. I do not use it for EML, or for package status tracking, or for the website. I have a column named "who2bug" in my pkg_mgmt that serves this purpose of sorting datasets. And that is not even the same use. (who2bug is not always the dataset owner.) 

I would approve of removing that column, DataSet.Investigator, if others want to. There are a lot of vestigial columns in tables. I can see how those get in the way for new users. I learned years ago to ignore them. Now it is time to clean house. 

2.
DataSetEntities.DataAnomalies
I have not used this column myself. My guess is it is associated with GCE Toolbox. Wade populates his entity metadata from Toolbox and a big feature of that app is to identify or flag anomalies. Just because I do not use it does not mean delete it. Does the SBC example data have anything in that column?

Can we change the name of this issue to Vestigial Columns?

**Comment by atn38** [comment]
@gastil you are indeed watching these issues! I changed issue name as you suggested. My POV is mostly that of the R code person: these are columns in metabase that people might find useful, populate with info, and then wonder why the R code doesn't do anything with them. It seems that some of them might be indeed vestigial!
re: DataAnomalies, yes SBC has one record: "The text table is 1.6 gb, and has been compressed to 365 mb for download."

I updated issue with another bunch!

**Comment by atn38** [comment]
I updated this a while ago to group by table in the main schema `lter_metabase`. I haven't looked closely at `pkg_mgmt` yet. @gastil @mob any columns I listed here you think we should KEEP? If none, I will start pruning (to clean the slate now that we're about to add a bunch of stuff in!)

**Comment by gastil** [comment]
**1. DataSet**
- Investigator
I vote for (2) drop column. Reason: redundant to DataSetPeople.

- Accession
I vote to drop this column. Neither SBC nor MCR use it. I am guessing it pre-dates EML and the packageIds. 

- ProjectRelease/PublicRelease
I vote drop ProjectRelease, keep PublicRelease.
Depends if you want to use this for pubDate. Where do you currently store and update pubDate? I would drop ProjectRelease (as I do not know what that even is.) I do use a column equivalent to PublicRelease in my other, pre-metabase, db which controls whether a dataset gets listed yet in the catalog. This allows drafts to exist before they are visible to the public. Wade had a timer ticking and 2 years after receipt, a dataset would plop into the catalog on its own on the PublicRelease date. My system is not that sophisticated. 

- geographicDescription
I vote drop. It is stored elsewhere. Redundant.

**2. DataSetEntities**
- DataAnomalies
I vote Undecided.
I feel like we should some day be able to record and report data anomalies. This info might be going into <additionalInfo>, guessing from that SBC example. I do not know if additionalInfo will make it into the EML Profile. I find it very useful for some datasets.  But the column name does not clearly match that use. 

- EntityRecords
I vote keep. I use it. I depend on it. The views for writeEML (written in perl and in production) use it. 

**3. DataSetAttributes**
- AttributeID
I vote keep it. I use it. In EML, the attributeName is NOT always the same thing as the attributeID, especially when you have the same attributeName in more than one entity in a dataset. In EML, every id must be unique. Sometimes you will see water_temp1 in one table and water_temp2 in another, or a common pattern for id's is entityname.attributename, as in bottle_data.depth and ctd_cast.depth for two entities, bottle_data and ctd_cast.

----- DataSetKeywords and DataSetPersonnel look good -----
- I'll take your word for it

**4. DataSetMethods**
- effectiveRange
I vote drop it. I did not even notice it existed. My guess it is detection range of an instrument.

**4. DataSetSites**
- EntitySortOrder
That is ei. Keep it. See explanation under DataSetTemporal.

- GeoCoverageSortOrder
It determines what order the geographic coverage entries are put into the EML doc. Yes, it does matter. Not just in the listing of the content, but also in the auto-generation of the KML that drives the little map. I prefer the sites to be listed in an order, not random. And if you ever want to tag one of those with, say, for example, semantic annotation, then you gotta have an index to the instance tag. (As in "done at" vs "collected from".) In the full design, entity-level anything is not in a table that does not have the string Entity in it; but I realize in the mini design that no longer holds true.

Also, writeEML does use this, from the view mb2eml.vw_eml_geographiccoverage. 

**6. DataSetTemporal**

- EntitySortOrder
In the consolidation of tables from full to mini, this device was invented: if you put null for ei then it goes at dataset level. If you have a non-null ei, then that row is going in at entity level. In the full model there was a separate table for entity-level and attribute-level stuff, such as coverages. I'm ok with this clever device. But it will need careful documentation.  

----- EMLAttributeCodeDefinition, EMLKeywordTypeList, EMLMeasurementScaleList, EMLNumberTypeList, EMLStorageTypeList look good ------

**7. EMLUnitDictionary**

-id
I would be ok with removing the id if everyone else is ok with using the name column for the primary key instead. In MCR also, all my id values are identical to the name value. If you remove id, do please be sure the PRIMARY KEY is moved to name.

- custom
Ask Margaret. In the MCR content I actually do list which units are also represented in the standardUnit list in EML. She worked hard on the standard units for EML2.2 so she may have some use for recording this. I'll go with her vote.

I will finish this next week. Not done.

**Comment by gastil** [comment]
Yes we do need to keep some of those columns.
See my notes I entered just now.

**Comment by atn38** [comment]
@gastil, more comments on this? You left off at EMLUnitDictionary.

**Comment by atn38** [comment]
Closing to declutter. An and Gastil has since cleaned up some of this stuff. See [this script](https://github.com/lter/LTER-core-metabase/blob/master/sql/12_alter_columns.sql)
