### ISSUE TITLE
site description in VIEW

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#28]
column geographicdescription in vw_eml_geographic appears hardcoded in .sql to be format "SiteList.SiteName: SiteList.SiteDesc"

from 2_create_schemas_tables.sql
```
(((s."SiteName")::text || ': '::text) || (s."SiteDesc")::text) AS geographicdescription;
```

SiteDesc isn't required. If NULL, should geographicdescription be NULL or should it be just SiteName with no colon?

**Comment by gastil** [comment]
Glad you mentioned this. I take the ID out of the geographic description
manually. I forgot it is in the view. I will customize mine. SBC likes
their ID to show. Although description is optional I would make a practice
of always populating it. I would suggest coalesce with the Id.

**Comment by twhiteaker** [comment]
SiteName is required, so there should always be at least the site name in geographicdescription.  Therefore, I think the view should have something like an if-else statement that says,

If SiteDesc isn't null, then use SiteName: SiteDesc; otherwise, use SiteName.

**Comment by gastil** [comment]
Not if/else. Use coalesce. There are complex situations that do warrant if/else but this is not one of them. The coalesce() function is built for this purpose.

**Comment by twhiteaker** [comment]
So then, how about this:

```sql
COALESCE("SiteName" || ': ' || "SiteDesc", "SiteName") AS geographicdescription;
```

**Comment by gastil** [comment]
--or 
s."SiteName" || coalesce(': '||s."SiteDesc",''); 
-- if that is the output you want, SBC style. For MCR, I'll go with the following
coalesce(s."SiteDesc",s."SiteName");
-- since in my instance my SiteNames are redundant to the first bit of the description. That is, all my descriptions begin with something like 'LTER 1 is...' so putting 'LTER 1: LTER 1 is...' is bad. YMMV.

**Comment by twhiteaker** [comment]
In the official repo, will you please put one or the other or your suggested solutions?  Either one is better than what is currently there.  We can explain how those fields are used in the documentation.
