### ISSUE TITLE
V1: consider refactoring script 02 (creates tables and views) into 2 scripts

### ISSUE THREAD

**Issue by mobb** [lter/LTER-core-metabase#32]
pros: 
the views are the most flexible. so it might make sense to pull their creation out into a separate script, so they are easier to recreate. during install views could be loaded last (after controlled/sample content loading). 

cons: 
there is no db-mgt scenario that is not interactive at some level. The db_owner will always need to know how to handle a particular script. so how we gather them up may be immaterial.

**Comment by gastil** [comment]
Agree. And if the user does want to next... next... finish the install, they can concatenate the scripts before loading. 

Given the special nature of maintaining SQL in a repository, it seems more sustainable to have separate parts that can load in sequence than one humongous beast of a script.

**Comment by twhiteaker** [comment]
+1 to have separate parts rather than a huge beast for @gastil 's reasons.  

However, regarding views, I don't think we can follow the practice of saving views to the end, as that violates our M.O. of "Any change is put into a new script with the next higher number in the filename."

Hmmm, unless we do something like:
0000-4999 = the meaty scripts
5000-9999 = views

**Comment by mobb** [comment]
I was imprecise - views would be loaded last in the initial install (edited comment above)

**Comment by gastil** [comment]
Tim I'm glad you are holding us to our organizational plan of ALTER between major revisions. VIEWs differ from TABLEs in regards to ALTER statements. One can ALTER the name of a view, the name of a column, or what schema the VIEW is in. But for changes to the query (SELECT and below), a CREATE OR REPLACE is required; that cannot be done with an ALTER. So we may see some REPLACE type changes between major versions.

**Comment by atn38** [comment]
+1 for separating creation of TABLEs and VIEWs. Especially if we eventually revise naming schemes for tables and columns, not to mention dropping/adding columns (see #27, #31, #38, #26 for relevant issues).

**Comment by atn38** [comment]
I messed with this a bit: not time consuming at all! All it took me is two `pg_dump` calls from an installed DB, one specifying the `mb2eml_r` schema and one specifying all schemas _but_ that one. Then some clever multi-line editing to edit out the existing users and the `%db_owner%` bit. (There's some views in `pkg_mgmt` as well but as we haven't done anything with them so far I left them alone.)

I do think that we should hold this off after the schema has stabilized. There's no point in refactoring `01.sql` as it is now and pushing the VIEWs part to the end, as some middle scripts now under the sequential model contain `CREATE OR REPLACE VIEW` statements.

**Comment by gastil** [comment]
To live migrate date type of a column that is used in a VIEW, one has to drop and reload. If the VIEW installation can be done in a later step than CREATE TABLEs, then those type of ALTER statements can be done before loading the VIEWs, solving that problem. 

So I do advocate for splitting create table and create view parts of the install script. But also to make those from a dump script farther along, but before Version 1.0.

**Comment by gastil** [comment]
These split-up install scripts were replaced by the OneBigFile installation.
