### ISSUE TITLE
see if installation includes PK for DataSetAttributes

### ISSUE THREAD

**Issue by gastil** [lter/LTER-core-metabase#49]
The testing install here at ucsb named mob_test_lter_core_mb_empty was lacking its PK on DataSetAttributes. 

This issue is a To-Do note for Gastil to check to be sure the install script does include that PK. 

If not, put this snippet in:

ALTER TABLE lter_metabase."DataSetAttributes"
  ADD CONSTRAINT "DataSetAttributes_PK_DataSetID_EntitySortOrder_ColumnName" 
  PRIMARY KEY ("DataSetID", "EntitySortOrder", "ColumnName");

A side issue is whether to use di ei ai or to use di ei aName. The di, ei and ai are integers but AttributeName is a string. Pros/cons either way. Currently both models are used because it came from GCE that way.

**Comment by atn38** [comment]
Closing because Gastil found the reason for why constraints weren't showing up.
