### ISSUE TITLE
adapting code versioning to SQL

### ISSUE THREAD

**Issue by gastil** [lter/LTER-core-metabase#50]
git (or any code versioning system) is not designed for SQL. When a new file is seen by git, it says "no problem, no conflict, this will not change existing code in master". But if that new file starts out with 

DROP VIEW a;
DROP VIEW b;
CREATE VIEW c AS ...

git has no way of seeing that no-no-no-no that new file DOES conflict with what is currently in master. So, we as humans will need to supervise git. Don't merge just cause git says there is no conflict. 

This has been a public service announcement from your local git newbie sql geek.

**Comment by gastil** [comment]
One way of informing git of such conflicts would be to commit revised copies of the VIEWs being dropped, with one line added below their CREATE statement, with a DROP statement. 

The particular instance that brought this up I'm not in favor of the DROPs. But in future I may well want to drop a VIEW. So then I'll commit a revised file that had contained that VIEW's create, with a DROP added. Then it will be clear to the reviewer that the merge can not be automatic.

**Comment by atn38** [comment]
this is what I'm trying to get at with my current plan of "let's review all current standing pull request, and then I will merge all schema-design code into one big file, then we edit that file directly." 

As in, we will be able to use git's DIFF functionalities.

**Comment by gastil** [comment]
Whether one-big-file or one file per table, neither will keep git from mistakenly saying a commit has no conflict when it actually does. This is going to have to be handled by us humans following rules we will have to set for ourselves. git can be used for lots of the process, but not for knowing if there are code conflicts. git was written for procedural code.

**Comment by gastil** [comment]
This is a note to myself (gastil), not an action item for anyone. I am recording the pg_dump command options and flags I use to backup. We may choose other options in future. If we want to be able to diff versions of the dump files, we will need to do the dumps with the same options.

```
pg_dump --host hostname --port 5432 --username "db_owner" --no-password  --format plain --section pre-data --section data --section post-data --verbose --file "/path/to/dir/pg_backup_testing_lter_core_mb_2019_06_18_11am.sql" "testing_lter_core_mb"
```

I changed the local-specific items hostname, username, path/to/dir. The output filename is my own convention, the same one I use for real system backups:

```pg_backup + db_name + date + aprox hour + .sql```

We may opt to separate the pre-data, data, and post-data dump into three files.

Advantage to 3 files:
- smaller files
- quick clarity where diffs occur

Advantage of 1 file:
- these have to be dumped and reloaded as a whole, not in part, usually
- can only test as a whole (or dump 3, load 3)
- only have to load one file
- only have to s/db_owner/local_username/ to one file

Since editing is likely to be within a test installation, not as an external text .sql file, we would only be opening a tiny part of the whole for editing at any one time, not the whole dump file. 

So, I'm thinking all-one-file.

**Comment by atn38** [comment]
An and Gastil two alternative ways of using Git to version SQL:
- ALTER statements defining changes between commits
- Using one big dump of a whole database installation after each set of ALTERs have been applied.

After extensive testing we need both. One big dump does show useful differences if always dumped from the same Postgres installation with the same `pg_dump` parameters. Dumps from PG 9 (Gastil) and PG 11 (An) are too different to be useful. An is committing a full dump script with each set of commits. 

ALTER statements allow an existing installation to migrate live, to keep up-to-date with the master branch. Such as the ones live managed by @mob, @scelmendorf, @lkuiucsb
