### ISSUE TITLE
mentiond PostGRES in readme?

### ISSUE THREAD

**Issue by twhiteaker** [lter/LTER-core-metabase#6]
Is there anything PostGRES specific in our SQL scripts?  I suspect there is, or at least you couldn't use the same scripts directly for SQLite for example. If that 's the case, then we should declare that this is for PostGRES in the readme.

**Comment by mobb** [comment]
yes, each brand of rDBMS has some dialect of SQL. Not all brands of rDBMS support all SQL features.
