### ISSUE TITLE
add VersionInfo table

### ISSUE THREAD

**Issue by twhiteaker** [lter/LTER-core-metabase#7]
Fields:
* DatabaseVersion
* EMLVersion

**Comment by mobb** [comment]
chat monday about what this should look like. maybe call it Settings, per
 https://enterprisecraftsmanship.com/2015/08/10/database-versioning-best-practices/

**Comment by twhiteaker** [comment]
Here's my stream of thoughts as I just finished the article.

I didn't see any justification for calling the table Settings. Doesn't VersionInfo seem more accurate?  I guess if we add other stuff to this table besides the version info that Settings would make more sense.

I like the convention of numbering the script but also including a text description in the filename that explains the change. 

Is it possible that we would ever change the database design or reference data so drastically that you couldn't perform that change with a SQL script?  If so, then I like our [proposed plan of having subfolders for major versions with numbered scripts beneath them](https://github.com/lter/LTER-core-metabase/issues/3), but maybe instead of v1.0.0-to-v1.0.1.sql we would have 02_UpdateUnits, where 02 is the minor version. So you'd have major version folders, with scripts for minor versions starting at 01 in each folder. 

In the Settings/VersionInfo table, you'd have a column for MajorVersion, MinorVersion, and EMLVersion.

**Comment by mobb** [comment]
from midway down the page, https://softwareengineering.stackexchange.com/questions/129569/how-to-incrementally-update-a-database-when-deploying-a-website

> 
> Anyway, back to the main point. It is quite possible to properly do that by creating a special table in your database, let's say X_VERSION, in which you will simply have the current version of the database schema (it may be a timestamp too). Whenever you alter your database schema, you put that change into a SQL script named [Timestamp-XXX-WhateverItIsYouAreDoing.sql], where:
> 
> Timestamp is the timestamp, for example 20110111-165500
> XXX is a number, which will be useful later to know the order of execution of the scripts
> Whatever, etc. is some text that will help you remember what you do in that script
> Whether your database updating program is in your application or outside does not matter for the following steps; whenever you deliver a new version of your application, your update program should do this:
> 
> Look up the current timestamp in X_VERSION
> Check all the scripts that must be executed between the version found in X_VERSION and the new version
> Loop over the scripts, and for each script
> 
> Execute the script updating your database/schema
> Update the timestamp in X_VERSION to the timestamp of the executed script
> When all scripts are done, you know your application can safely start.

**Comment by twhiteaker** [comment]
I like the idea of being able to compare the version number between the database and the scripts.  But to me, having both a timestamp and a version number is redundant.  

So how this for the scripts:

* Name the scripts X_WhateverItIsYouAreDoing.sql.  I don't think we need to zero pad these, do you?  
* Put the scripts under a major version folder, where major versions represent where we wanted a fresh start to the script pile.

And this for the database:

* Add a table called VersionInfo with these fields:
    * MajorVersion
    * MinorVersion
    * EMLVersion

**Comment by twhiteaker** [comment]
Here's a draft of the SQL.  Once this is committed, every subsequent script must update the VersionInfo table to reflect the new version it creates.

```sql
-- Note: FIRST: edit %db_owner% to the account name of the DB owner

--
-- Name: VersionInfo; Type: TABLE; Schema: lter_metabase; Owner: %db_owner%
--

CREATE TABLE lter_metabase."VersionInfo" (
    "MajorVersion" character varying(21) NOT NULL,
    "MinorVersion" character varying(21) NOT NULL,
    "EMLVersion" character varying(21) NOT NULL
);

ALTER TABLE lter_metabase."VersionInfo" OWNER TO %db_owner%;

--
-- Name: TABLE "VersionInfo"; Type: COMMENT; Schema: lter_metabase; Owner: %db_owner%
--

COMMENT ON TABLE lter_metabase."VersionInfo" IS 'Database Schema and EML version info';


--
-- Name: COLUMN "VersionInfo"."MajorVersion"; Type: COMMENT; Schema: lter_metabase; Owner: %db_owner%
--

COMMENT ON COLUMN lter_metabase."VersionInfo"."MajorVersion" IS 'Core metabase major version';


--
-- Name: COLUMN "VersionInfo"."MinorVersion"; Type: COMMENT; Schema: lter_metabase; Owner: %db_owner%
--

COMMENT ON COLUMN lter_metabase."VersionInfo"."MinorVersion" IS 'Core metabase minor version';


--
-- Name: COLUMN "VersionInfo"."EMLVersion"; Type: COMMENT; Schema: lter_metabase; Owner: %db_owner%
--

COMMENT ON COLUMN lter_metabase."VersionInfo"."EMLVersion" IS 'Ecological Metadata Language version to which this schema applies';


--
-- Data for Name: VersionInfo; Type: TABLE DATA; Schema: lter_metabase; Owner: %db_owner%
--

COPY lter_metabase."VersionInfo" ("MajorVersion", "MinorVersion", "EMLVersion") FROM stdin;
1	6	2.1
\.
```

**Comment by gastil** [comment]
I do see the use of a place to store version within the installation. Code could do a prelim query of the back end to ensure it is the version it knows it needs. Someday mb might get used widely enough that the person running it would not "just know". A few suggestions: drop Info from the name; it is all info. If major version will always be an integer, I'll suggest the data type be integer. Same for minor, except I've seen minor versions get fancier than just an integer. I do not know if our forks are minor revisions. The EML version currently is EML 2.1.1 not EML 2.1 so definitely cannot do a numeric field for that. I'll suggest that if/when someone does a major fork away from the lter core, that the comments will become obsolete. The comments refer to 'Core metabase...'. Whereas that itself is a version. Maybe the first column should be a string of the name of the database. I've seen five so far: GCE Metabase, mcr_metabase & sbc_metabase (the full version), sbc_metabase (the mini version), mini_metabase, and now lter_core_metabase. Maybe name that column VersionName? Then, what is the PK of this table? Do you want a dbupdatetime column that auto-fills with a trigger? (Im not sure lter_core_mb kept any of those except maybe mine from pkg_mgmt.) Note the EML version column could be multi-valued, as one metabase can support several EML versions. Actually many-to-many there. But I'll not suggest we normalize this to 4th order. Maybe add a notes or comment column or even a GitHub tagged release DOI? Or not. I see this table analogous to the postgres query ```select version();```

**Comment by twhiteaker** [comment]
> drop Info from the name

Agreed. "Version" is not a reserved keyword in Postgres.

> If major version will always be an integer, I'll suggest the data type be integer.

I think it will be. I think we can probably use integer for minor version, too. I don't think we'll be using [semantic versioning](https://semver.org/). I like our approach of having a major version and then having the minor versions match the number of the .sql file that brought us up to that version.

> Maybe the first column should be a string of the name of the database.

That sounds fine. It helps a user track that they've modified core mb.

> Then, what is the PK of this table?

Why would we need a PK for this table?

> Do you want a dbupdatetime column that auto-fills with a trigger?

No.  I think having the name and version numbers is enough.

> Note the EML version column could be multi-valued, as one metabase can support several EML versions.

I suspect we'll be targeting a specific version of EML, so I'd like this field to store the version we were targeting.  However, since this is text field, we could just make it long enough to hold a delimited list of support EML versions.

> Maybe add a notes or comment column or even a GitHub tagged release DOI? Or not.

I don't think it's necessary. But it would have nearly insignificant impact on database bloat, so I probably won't fight it if others feel strongly about including it.

**Comment by gastil** [comment]
Re: Tim's suggestion that we put the version of a given installation into a table, like a stamp or marker: I like this idea. I do not want to add another table just for this to the lter_metabase schema because we've already far exceeded the number of tables envisioned. Could we put this table into pkg_mgmt?

Over the past few months we seem to have settled into a pattern of SQL versioning. In summary: 

- Incremental changes which can be run on a "live" installation (an already installed and populated database) consist of ALTER statements to change tables & columns, UPDATE or INSERT FROM SELECT (aka select-into) to migrate data, or REPLACE OR CREATE VIEW sql. Incremental change sql files start with a 2-digit number, ie 16_this_to_do_that.sql. Im sure we'll change practice long before we hit 99. :)

- OneBigFile installation scripts are made with pg_dump from the postgres 11 installation at BLE after one or more incremental changes have been applied. For initial installation, use OneBigFile. To see diffs between commits, diff versions of the OneBigFile. (This does not work comparing pg_dump from the postgres 9 installation at UCSB because there's thousands of meaningless diffs.)

**Comment by gastil** [comment]
patch 22 creates pkg_mgmt.version_tracker_metabase. See the INSERT statement in that patch for an example of the INSERT we will now expect each patch sql script to contain.

Each time we apply a patch (by running the sql in the file) that file will automatically update this version table.
