### ISSUE TITLE
add default on semantic cross ref tables

### ISSUE THREAD

**Issue by mobb** [lter/LTER-core-metabase#76]
Gastil please add a DEFAULT to fill in "ObjectPropertyID" column when none is specified in the xref tables.

attribute-level: containsMeasurementsOfType (MB id for "contains measurements of type")
dataset-level:  IAO_0000136 (MB id for "is about")

**Comment by gastil** [comment]
done by revising 33_semantic_annotation.sql rather than making a new patch.
