### ISSUE TITLE
Create a best practices

### ISSUE THREAD

**Issue by mobb** [lter/LTER-core-metabase#8]
Here is a place to start
https://enterprisecraftsmanship.com/2015/08/10/database-versioning-best-practices/

**Comment by mobb** [comment]
some more refs and examples:
- short blog post:
  - https://www.quora.com/What-is-the-usual-methodology-for-using-Git-when-developing-in-SQL-Server-stored-procedures-triggers-etc

- example (popler is a posgtres db, ostensibly of LTER pop data)
  - https://github.com/bibsian/database-development

**Comment by mobb** [comment]
notes for BP
1. there three primary schemas, pkg_mgt, metabase and vw_mb2eml_r
    1. there are cross-refs between schemas
    2. Anticipate someone using only those three schemas
3. secondary schemas may be added (by committee) 
    1. cross-ref tables used by the secondary schemas should be in the secondary schemas (not added to primary)

**Comment by atn38** [comment]
closing and moving conversation to #50.
