### ISSUE TITLE
pkg_state, pkg_sort contain entire inventory of SBC instead of just 4 example rows

### ISSUE THREAD

**Issue by gastil** [lter/LTER-core-metabase#80]
A simple fix, but needs to be done on the dev installation from which OneBigFile is made. We accidentally included the entire inventory of 265 rows of pkg_state and 254 rows of pkg_sort from Margaret's copy of pkg_mgmt rather than just the 4 example datasets. 

```
delete from pkg_mgmt.pkg_core_area
where "DataSetID" < 99000 or "DataSetID" > 100000
;
delete from pkg_mgmt.pkg_core_area
where "DataSetID" < 99000 or "DataSetID" > 100000
;
delete from pkg_mgmt.pkg_sort
where "DataSetID" < 99000 or "DataSetID" > 100000
;
```
Just run that one time on the dev installation. Do not make a patch.

**Comment by atn38** [comment]
on it. this will be lumped in with the 35 patch
note the edit below
```
delete from pkg_mgmt.pkg_core_area
where "DataSetID" < 99000 or "DataSetID" > 100000
;
delete from pkg_mgmt.pkg_state
where "DataSetID" < 99000 or "DataSetID" > 100000
;
delete from pkg_mgmt.pkg_sort
where "DataSetID" < 99000 or "DataSetID" > 100000
;
```
