### ISSUE TITLE
drop unique constraint on DataSet column Revision

### ISSUE THREAD

**Issue by gastil** [lter/LTER-core-metabase#82]
We accidentally left in place an old UNIQUE constraint on the Accession column of DataSet. Now that we use that column for Revision, and obviously it will be common for 2 datasets to have the same revision.

ALTER TABLE lter_metabase."DataSet"
  DROP CONSTRAINT "IX_DataSet_Accession" UNIQUE("Revision");
This has to be done on the installation from which OBF is generated.

**Comment by atn38** [comment]
Loving and also a tad dismayed at how many bugs you guys are finding!

**Comment by gastil** [comment]
Li is finding them. I just enter the issues. Yes wonder. Yes dismay! So
very glad I delayed the announcement! Li gave up. She will try agin after
we do some clean up. More issues coming. I had to reboot.

**Comment by atn38** [comment]
on it

**Comment by atn38** [comment]
note that the SQL statement as written above gives an error. Only the constraint name needs to be specified:

```
ALTER TABLE lter_metabase."DataSet"
DROP CONSTRAINT "IX_DataSet_Accession";
```
