### ISSUE TITLE
change "DataSetMethodSteps" table name to "DataSetMethod"

### ISSUE THREAD

**Issue by lkuiucsb** [lter/LTER-core-metabase#83]
To follow the habit of inputting information in the "method", could we change the table names to "DataSetMethodStepsInstruments", "DataSetMethodStepsProtocols"...and two other tables. In this case, the methodSteps table will be (and should be ) the first one among all the other method related tables.

**Comment by gastil** [comment]
We discussed this. The suggestion is to rename DataSetMethodSteps to DataSetMethod. The motivation is that the parent table will alphabetically sort before its child tables. We agreed not to go to lengths to make other parent child related tables also sort alphabetically. Just this one.

```
ALTER TABLE lter_metabase."DataSetMethodSteps"
  RENAME TO "DataSetMethod";
```

**Comment by atn38** [comment]
we've had the "DataSet is singular" conversation I think :)
on it

**Comment by atn38** [comment]
implemented, closing
