### ISSUE TITLE
create scripts to populate controlled vocab tables

### ISSUE THREAD

**Issue by mobb** [lter/LTER-core-metabase#9]
- [ ] lter_metabase.EMLUnitDictionary
- [ ] lter_metabase."KeywordThesaurus"
- [ ] lter_metabase."Keywords" (some)
- [ ] lter_metabase."EMLKeywordTypeList"
- [ ] lter_metabase."EMLMeasurementScaleList"
- [ ] lter_metabase."EMLNumberTypeList"
- [ ] lter_metabase."EMLStorageTypeList"
- [ ] lter_metabase."EMLUnitTypes"
- [ ] lter_metabase."MeasurementScaleDomains"

**Comment by mobb** [comment]
done, included in the core with examples

**Comment by twhiteaker** [comment]
@mobb Are you pushing these changes to GitHub?  I'm still only seeing a docs folder, a license file, and a readme file. No scripts.

**Comment by twhiteaker** [comment]
How about including a standalone script that populates tables with example data?

**Comment by mobb** [comment]
maybe. but like the controlled content, upload scripts take more time than pruning. ignoring the 4-5 sample datasets is pretty easy, and including them means they are always available.  someone who wanted them removed (from your own instance) could prune them out.
