### ISSUE TITLE
add "docbook" to be an abstract and method description type

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#90]
I'd like the option to store `docbook` formatted text in metabase, for direct insertion into EML docs down the pipeline. Partly motivated by me finding out that markdown doesn't support sub/superscripts very elegantly.

**Comment by gastil** [comment]
Good news An: core-mb already supports that. The column "method_xml" is for `docbook` formatted text. When we put text into `<abstract>` or `<methodStep>`, that part of the xml subtree that goes there, that IS `docbook`.

**Comment by atn38** [comment]
good point gastil, but isn't the column method_xml meant to contain the
_whole_ methods tree, not just description? i.e. multiple method steps,
provenance, the whole works?

**Comment by atn38** [comment]
patch 39 modifies this constraint

**Comment by atn38** [comment]
closing
