### ISSUE TITLE
ListSites.AltitudeUnits char limit too short

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#91]
currently character limit is 10, need to be 100 to match that of DataSetAttributes.Unit which is the only other place with units in metabase

I'll update this issue with a patch shortly, posting to alert people.

**Comment by atn38** [comment]
see commit 8c69107255547301a3769d4cc7b62b18c4140fe4 for patch40

**Comment by atn38** [comment]
see commit 1276bba22a96f81dd5a3b1bb9fa27631a27832a8 for patch40

**Comment by atn38** [comment]
see 1276bba22a96f81dd5a3b1bb9fa27631a27832a8 for patch40.

**Comment by gastil** [comment]
I do not understand. Not objecting, just want to understand. Altitude units are expected to be one of {feet, meters, miles, kilometers}. I cannot think of an altitude unit with more than 10 characters. So maybe Postgres complained that a foreign key to the unit dictionary needed to match the length of characters? Does EML actually use units in the schema like stmml units (customUnit or standardUnit)? I have only ever used `<altitudeUnits>meter</altitudeUnits>`. Perhaps a CHECK unitName in ('meters','kilometers','feet','miles') is better than an FK?

I looked at common patterns of usage. In 30 scopes (just Lter, not edi), the following units are used: meter, meters, foot, Foot_US.

**Comment by atn38** [comment]
Ah yes, I forgot to mention that I did run into an error when editing the
EMLUnitDictionary. It complained that what I'm editing makes it too long
because AltitudeUnits only has a 10 char limit. Sorta preemptive action, I
thought. Nothing happens if I leave the units alone. Weird.

**Comment by atn38** [comment]
closing
